import express from "express";
import { checkUsername, login, logout, signup, updateProfile } from "../controllers/auth.controller.js";
import protectRoute from "../middleware/protectRoute.js";
const router = express.Router();
router.post("/signup", signup);
router.post("/login", login);
router.post("/logout", logout);
router.post("/check-username", checkUsername);
router.put("/update-profile", protectRoute, updateProfile);
export default router;